# Generated by Django 2.2.10 on 2020-12-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='finish_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата старта'),
        ),
    ]
